### ISSUE TITLE
Facebook: Rewrite existing villains bios

### ISSUE THREAD

**Issue by krkimery** [krkimery/krkimery.github.io#23]
Improve on temporary content

**Comment by Shadiat** [comment]
fixed and rewrote for all profiles

**Comment by krkimery** [comment]
Existing bios are placeholders. The jokes, puns, etc are just there until someone can actually write up real, not-plagiarized bios for each of the facebook pages. They don't need to be long, but the content on the pages should be accurate, if possible, and mostly serious.
