### ISSUE TITLE
Facebook: Rewrite existing bios for organizations

### ISSUE THREAD

**Issue by krkimery** [krkimery/krkimery.github.io#24]
Improve the temporary bios for each of the organizations.

**Comment by Shadiat** [comment]
rewrote all bios for old and new

**Comment by krkimery** [comment]
Existing bios are placeholders. The jokes, puns, etc are just there until someone can actually write up real, not-plagiarized bios for each of the facebook pages. They don't need to be long, but the content on the pages should be accurate, if possible, and mostly serious.
