### ISSUE TITLE
Add html titles for FB profile pages

### ISSUE THREAD

**Issue by robertocfz** [krkimery/krkimery.github.io#47]

**Comment by krkimery** [comment]
What do you mean by this specifically?

**Comment by robertocfz** [comment]
The FB pages don't have <title></title> tags so when you open the page, you'll notice on the browser tab it will say something like "ineedahertosave.me/heroes.html" and not something like "Spiderman Profile!" If you look at splash page or my model pages and they'll say something like "Organizations" for the title.
![pic](https://cloud.githubusercontent.com/assets/25283658/24687072/40778e62-197d-11e7-845a-8b9e30fdc469.JPG)
