### ISSUE TITLE
Make sorting more visable

### ISSUE THREAD

**Issue by robertocfz** [krkimery/krkimery.github.io#48]
Currently, nothing on the model pages indicates that clicking on the cells in the first row (Real Name, Alias, Birth Place, etc.) is will sort the tables for those columns. Perhaps add text or a sorting box?

![image](https://cloud.githubusercontent.com/assets/22090967/24686640/d0fc8ed6-197a-11e7-9e44-e3a4d9eda052.png)

**Comment by ivymarkwell** [comment]
I have added a simple up and down arrow like in the picture with this functionality. The actual arrow can be changed very easily if we want a different shape.
